#!/bin/sh

check_suspend()
{
	[ -c /dev/pmu ] && return 0
	grep -q mem /sys/power/state && return 0
}

do_suspend()
{
	if [ -c /dev/pmu ]; then
		pm-pmu --suspend
	else
		echo -n "mem" > /sys/power/state
	fi
}

check_hibernate()
{
	[ -f /sys/power/disk ] && grep -q disk /sys/power/state
}

do_hibernate()
{
	[ -n "${HIBERNATE_MODE}" ] && \
	grep -qw "${HIBERNATE_MODE}" /sys/power/disk && \
	echo -n "${HIBERNATE_MODE}" > /sys/power/disk
	echo -n "disk" > /sys/power/state
}

check_suspend_hybrid()
{
	return 1
}

do_suspend_hybrid()
{
	return 1
}
