#!/bin/sh

[ -x /sbin/hdparm ] || exit $NA

harddrive_ac () {
    for dev in /dev/[hs]d[a-z]; do
	# disable write caching, do not spin down the drive, disable APM 
	# and acoustic management, and sync everything to drive.
	hdparm -W 0 -S 0 -B 254 -M 254 -f -F $dev
    done
}

harddrive_battery() {
    for dev in /dev/[hs]d[a-z]; do
	# disable write caching, enable acoustic management
	hdparm -W 0 -M 128 $dev
    done
}

case $1 in
    true) harddrive_battery ;;
    false) harddrive_ac ;;
    *) exit $NA ;;
esac

exit 0
