#!/bin/sh

VM="/proc/sys/vm"

[ -f $VM/laptop_mode -a -f $VM/dirty_ratio ] || exit $NA

laptop_mode_ac() {
    echo 0 >$VM/laptop_mode
    echo 5 >$VM/dirty_background_ratio
    echo 2999 >$VM/dirty_expire_centisecs
    echo 10 >$VM/dirty_ratio
    echo 499 >$VM/dirty_writeback_centisecs
}

laptop_mode_battery() {
    echo 1 >$VM/laptop_mode
    echo 1 >$VM/dirty_background_ratio
    echo 60000 >$VM/dirty_expire_centisecs
    echo 85 >$VM/dirty_ratio
    echo 60000 >$VM/dirty_writeback_centisecs
}

case $1 in
    true) laptop_mode_battery ;;
    false) laptop_mode_ac ;;
    *) exit $NA ;;
esac

exit 0
