#!/bin/bash

git log  --pretty=format:"pm-utils (%ct.%h) unstable; urgency=low%n%n  * %s%n%n -- %an <%ae>  %aD%n" --no-merges >debian/changelog && \
autoreconf --install && \
./configure && \
dpkg-buildpackage && echo "pm-utils .deb file created in parent directory." || \
    echo "Something went wrong creating .deb."
