#!/bin/sh

[ -f /proc/acpi/ibm/led ] || exit 0;

case "$1" in
	suspend)
		echo "7 blink" > /proc/acpi/ibm/led > /dev/null 2>&1 ;;
	resume) 
		echo "7 off"   > /proc/acpi/ibm/led > /dev/null 2>&1 ;;
esac

exit $?
