#!/bin/bash

. /etc/pm/functions

suspend_bluetooth()
{
	if [ -f /proc/acpi/ibm/bluetooth ]; then
		savestate ibm_bluetooth $(awk '{ print $2 ; exit; }' /proc/acpi/ibm/bluetooth)
		echo disable > /proc/acpi/ibm/bluetooth
	else
		savestate ibm_bluetooth missing
	fi
}

resume_bluetooth()
{
	case "$(restorestate ibm_bluetooth)" in
		enabled)
			echo enable > /proc/acpi/ibm/bluetooth
			;;
		disabled)
			echo disable > /proc/acpi/ibm/bluetooth
			;;
	esac
}

case "$1" in
	hibernate|suspend)
		suspend_bluetooth
		;;
	thaw|resume)
		resume_bluetooth
		;;
	*)
		;;
esac

exit $?
