#!/bin/bash

. /etc/pm/functions

suspend_modules()
{
	[ -z "$SUSPEND_MODULES" ] && return 0
	for x in $SUSPEND_MODULES ; do
		/sbin/rmmod $x >/dev/null 2>&1 0<&1
	done
	return 0
}

resume_modules()
{
	[ -z "$SUSPEND_MODULES" ] && return 0
	for x in $SUSPEND_MODULES ; do
		/sbin/modprobe $x >/dev/null 2>&1 0<&1
	done
	return 0
}

case "$1" in
	hibernate|suspend)
		suspend_modules
		;;
	thaw|resume)
		resume_modules
		;;
	*)
		;;
esac

exit $?
