#!/bin/bash

. /etc/pm/functions

suspend_modules()
{
	[ -z "$SUSPEND_MODULES" ] && return 0
	for x in $SUSPEND_MODULES ; do
		modunload $x
	done
	return 0
}

resume_modules()
{
	[ -z "$RESUME_MODULES" ] && return 0
	for x in $RESUME_MODULES ; do
		modprobe $x
	done
}

case "$1" in
	hibernate|suspend)
		suspend_modules
		;;
	thaw|resume)
		resume_modules
		;;
	*)
		;;
esac

exit $?
