#!/bin/bash


get_lcd_status()
{
	if [ ! -x /usr/sbin/radeontool ]; then
		echo "error"
		return 2
	fi
	STATUS=$(/usr/sbin/radeontool light | cut -d\  -f5 2>/dev/null)
	RETVAL=0
	case "x$STATUS" in
		"xon")
			echo "on"
			RETVAL=0
			;;
		"xoff")
			echo "off"
			RETVAL=1
			;;
		*)
			echo "error"
			RETVAL=2
			;;
	esac
	return $RETVAL
}

lcd_off()
{
	if [ "$(get_lcd_status)" != "on" ]; then
		return
	fi
	[ -x /usr/sbin/radeontool] && /usr/sbin/radeontool light off
}

lcd_on()
{
	if [ "$(get_lcd_status)" != "off" ]; then
		return
	fi
	[ -x /usr/sbin/radeontool ] && /usr/sbin/radeontool light on
}

get_crt_status()
{
	if [ ! -x /usr/sbin/radeontool ]; then
		echo "error"
		return 2
	fi
	STATUS=$(/usr/sbin/radeontool light | cut -d\  -f5 2>/dev/null)
	RETVAL=0
	case "x$STATUS" in
		"xon")
			echo "on"
			RETVAL=0
			;;
		"xoff")
			echo "off"
			RETVAL=1
			;;
		*)
			echo "error"
			RETVAL=2
			;;
	esac
	return $RETVAL
}

crt_off()
{
	if [ "$(get_lcd_status)" != "on" ]; then
		return
	fi
	[ -x /usr/sbin/radeontool ] && /usr/sbin/radeontool dac off
}

crt_on()
{
	if [ "$(get_lcd_status)" != "on" ]; then
		return
	fi
	[ -x /usr/sbin/radeontool ] && /usr/sbin/radeontool dac on
}

[ -x /usr/sbin/vbetool ] || return

suspend_video()
{
(
	/usr/sbin/vbetool dpms suspend
) >/dev/null 2>&1
}

resume_video()
{
(
	/usr/sbin/vbetool dpms on
) >/dev/null 2>&1
}
