#!/bin/sh

. "${PM_FUNCTIONS}"

do_add_quirks()
{
	add_parameters $(lshal | \
	awk -F '[. ]' \
		'/  power_management.quirk.[a-z_]+ = true/ \
			{gsub(/_/, "-", $5); printf("--quirk-%s", $5)}')
}
	
mabye_add_quirks()
{
	[ -z "$PM_CMDLINE" ] && {
		do_add_quirks
		return 0
	}
	for p in ${PM_CMDLINE}; do
		[ "$p" = "--auto-quirks" ] || continue
		do_add_quirks
		remove_parameters --auto-quirks
	done
}

help()
{
	echo
	echo "Auto quirk handler option:"
	echo
	echo "  --auto-quirks"
	echo "  Running without any options will also invoke auto quirk."
}

case $1 in
	suspend|hibernate) mabye_add_quirks ;;
	help) help ;;
	*) exit $NA ;;
esac

