#!/bin/sh

. "${PM_FUNCTIONS}"

case "$1" in
	hibernate|suspend)
		fgconsole |savestate console
		chvt 63
		;;
	thaw|resume) 
		state_exists console || exit 1
		chvt $(restorestate console) 
		deallocvt 63
		;;
	*)
		;;
esac
