#!/bin/bash

case "$1" in
 	hibernate|suspend)
		# save the old loglevel
		read KERNEL_LOGLEVEL DUMMY < /proc/sys/kernel/printk
		echo "export KERNEL_LOGLEVEL=$KERNEL_LOGLEVEL" >> /var/run/pm-suspend
		# set the loglevel so we see the progress bar.
		# if the level is higher than needed, we leave it alone.
		if [ $KERNEL_LOGLEVEL -lt 5 ]; then
        		 echo 5 > /proc/sys/kernel/printk
		fi

		echo "$1 initiated: `date`"
		echo
		echo "`uname -a`"
		echo "kernel command line: '`cat /proc/cmdline`'"
		echo "`lsmod`"
		echo
		echo "`free`"
		echo
		;;
	thaw|resume)
		if [ -n "$KERNEL_LOGLEVEL" ] ; then
		 	echo $KERNEL_LOGLEVEL > /proc/sys/kernel/printk
		fi
		;;
	*)
		;;
esac


exit 0
