#!/bin/sh

[ -f /proc/acpi/ibm/led ] || exit 1

case "$1" in
	hibernate|suspend)
		echo "7 blink" >/proc/acpi/ibm/led
		;;
	thaw|resume) 
		echo "7 off" >/proc/acpi/ibm/led
		;;
	*)
		;;
esac

exit $?
