#!/bin/bash

. "${PM_FUNCTIONS}"

command_exists rcautofs || exit $NA

case "$1" in
	hibernate|suspend)
		stopservice autofs
		;;
	thaw|resume)
		restartservice autofs
		;;
	*) exit $NA
		;;
esac

exit $?
