#!/bin/sh

. "${PM_FUNCTIONS}"

[ -f /proc/acpi/ibm/bluetooth ] || exit $NA

suspend_bluetooth()
{
	savestate ibm_bluetooth "$(awk '{ print $2 ; exit; }' /proc/acpi/ibm/bluetooth)"
	echo disable > /proc/acpi/ibm/bluetooth
}

resume_bluetooth()
{
	case "$(restorestate ibm_bluetooth)" in
		enabled)
			echo enable > /proc/acpi/ibm/bluetooth
			;;
		disabled)
			echo disable > /proc/acpi/ibm/bluetooth
			;;
	esac
}

case "$1" in
	hibernate|suspend)
		suspend_bluetooth
		;;
	thaw|resume)
		resume_bluetooth
		;;
	*) exit $NA
		;;
esac
