#!/bin/sh

. /usr/lib/pm-utils/functions

suspend_bluetooth()
{
	[ -f /proc/acpi/ibm/bluetooth ] || return 1
	savestate ibm_bluetooth "$(awk '{ print $2 ; exit; }' /proc/acpi/ibm/bluetooth)"
	echo disable > /proc/acpi/ibm/bluetooth
}

resume_bluetooth()
{
	case "$(restorestate ibm_bluetooth)" in
		enabled)
			echo enable > /proc/acpi/ibm/bluetooth
			;;
		disabled)
			echo disable > /proc/acpi/ibm/bluetooth
			;;
	esac
}

case "$1" in
	hibernate|suspend)
		suspend_bluetooth
		;;
	thaw|resume)
		resume_bluetooth
		;;
	*)
		;;
esac

exit $?
