#!/bin/bash
#
# Prevent lease timing out for networks controlled by ifup/ifdown
# bnc#603291
#

. "${PM_FUNCTIONS}"

# Sanity checks
[ -x /etc/init.d/network ] || exit $NA

# NetworkManager is handled by 55NetworkManager via dbus.
# This script handles only netcontrol alias sysconfig alias ifup.
network_service_id=`systemctl --no-pager -p Id show network.service 2>/dev/null`
case ${network_service_id#Id=} in
	# /etc/init.d/network is active
	network.service)	;;
	# network.service is an alias link
	# e.g. to the NetworkManager
	*) exit $NA		;;
esac

case "$1" in
    hibernate|suspend)
	# use /etc/init.d/network directly here
	/etc/init.d/network stop-all-dhcp-clients
        ;;
    thaw|resume)
	# use /etc/init.d/network directly here
	/etc/init.d/network restart-all-dhcp-clients
        ;;
    *) exit $NA
        ;;
esac

