#!/bin/sh

. /usr/lib/pm-utils/functions

resume_batteries()
{
	for x in $(hal-find-by-capability --capability battery 2>/dev/null); do
#		hal-set-property --udi "$x" --key battery.present --bool false
#		dbus-send --print-reply --system --reply-timeout=2000 \
#			--dest=org.freedesktop.Hal $x \
#			org.freedesktop.Hal.Device.Reprobe string:$x
		dbus-send --print-reply --system --reply-timeout=2000 \
			--dest=org.freedesktop.Hal $x \
			org.freedesktop.Hal.Device.Rescan string:$x
	done
}

case "$1" in
	resume|thaw)
		resume_batteries
		;;
esac
