#!/bin/sh

. "${PM_FUNCTIONS}"

command_exists alsactl || exit $NA

case "$1" in
	hibernate|suspend)
		alsactl store 0 >/dev/null 2>&1
		;;
	thaw|resume) 
		alsactl restore 0 >/dev/null 2>&1
		;;
	*) exit $NA
		;;
esac
