#!/bin/sh

. "${PM_FUNCTIONS}"

command_exists alsactl || exit 1

case "$1" in
	hibernate|suspend)
		alsactl store 0 >/dev/null 2>&1
		;;
	thaw|resume) 
		alsactl restore 0 >/dev/null 2>&1
		;;
	*)
		;;
esac

exit $?
