#!/bin/sh
. /usr/lib/pm-utils/functions

NTPD_LOCK=/tmp/.pm-ntpd.lock
release_ntpd_lock() {
	rmdir "${NTPD_LOCK}"
}
suspend_clock() {
	if try_lock "${NTPD_LOCK}"; then
		trap release_ntpd_lock 0
		stopservice ntpd
	fi
	/sbin/hwclock --systohc >/dev/null 2>&1 0<&1
	return $?
}

resume_clock() {
	/sbin/hwclock --hctosys >/dev/null 2>&1 0<&1
	rc=$?
	# Bring back ntpd _after_ NetworkManager and such come back...
	( 	spin_lock "${NTPD_LOCK}";
		trap release_ntpd_lock 0
		sleep 20; 
		restartservice ntpd; ) &
	return $rc
}

case "$1" in
	hibernate|suspend)
		suspend_clock
		;;
	thaw|resume)
		resume_clock
		;;
	*)
		;;
esac

exit $?
