#!/bin/sh

. "${PM_FUNCTIONS}"


[ -d /sys/devices/system/cpu/ ] || exit 1

hibernate_cpufreq()
{
	( cd /sys/devices/system/cpu/
	for x in cpu[0-9]*/cpufreq/scaling_governor ; do
		[ -f "$x" ] || continue
		grep -q "$TEMPORARY_CPUFREQ_GOVERNOR" \
			"${x%/*}/scaling_available_governors" || continue
		savestate "${x%%/*}_governor" $(cat "$x")
		echo "$TEMPORARY_CPUFREQ_GOVERNOR" > "$x"
	done )
}

thaw_cpufreq()
{
	( cd /sys/devices/system/cpu/
	for x in cpu[0-9]*/cpufreq/scaling_governor ; do
		[ -f "$x" ] || continue
		local gov=$(restorestate "${x%%/*}_governor")
		[ -z "$gov" ] && continue
		echo "$gov" > "$x"
	done )
}

case "$1" in
	suspend|hibernate)
		hibernate_cpufreq
		;;
	resume|thaw)
		thaw_cpufreq
		;;
	*)
		;;
esac

exit $?
