#!/bin/sh

. /usr/lib/pm-utils/functions

hibernate_cpufreq()
{
	[ -d /sys/devices/system/cpu/ ] || return 1
	( cd /sys/devices/system/cpu/
	for x in cpu[0-9]* ; do
		[ -f "$x/cpufreq/scaling_governor" ] || continue
		grep -q "$TEMPORARY_CPUFREQ_GOVERNOR" \
			"$x/cpufreq/scaling_available_governors" || continue
		savestate "${x}_governor" $(cat "$x/cpufreq/scaling_governor")
		echo "$TEMPORARY_CPUFREQ_GOVERNOR" > \
			"$x/cpufreq/scaling_governor"
	done )
}

thaw_cpufreq()
{
	( cd /sys/devices/system/cpu/
	for x in cpu[0-9]* ; do
		local gov=$(restorestate "${x}_governor")
		[ -z "$gov" ] || continue
		echo "$gov" > "$x/cpufreq/scaling_governor"
	done )
}

case "$1" in
	suspend|hibernate)
		hibernate_cpufreq
		;;
	resume|thaw)
		thaw_cpufreq
		;;
	*)
		;;
esac

exit $?
