#!/bin/sh
#
# Copyright 2006-2007 Richard Hughes <richard@hughsie.com>
# Copyright 2007 Peter Jones <pjones@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.

. "${PM_FUNCTIONS}"

reset_brightness() {
	for bl in /sys/class/backlight/* ; do
		[ -f "$bl/brightness" ] || continue
		BR="$(cat $bl/brightness)"
		echo 0 > "$bl/brightness"
		echo "$BR" > "$bl/brightness"
	done
}

if command_exists vbetool; then
	vbe() { vbetool "$@"; }
else 
	vbe() { echo "vbetool not installed!" 1>&2; return 1; }
fi

if command_exists radeontool; then
	radeon() { radeontool "$@"; }
else 
	radeon() { echo "radeontool not found" 1>&2; return 1; }
fi

save_fbcon(){
	local con
	for con in /sys/class/graphics/*/state; do
		echo 1 >"${con}"
	done
}

resume_fbcon(){
	local con
	for con in /sys/class/graphics/*/state; do
		echo 0 >"${con}"
	done

resume_video()
{
	if [ "${DISPLAY_QUIRK_RADEON_OFF}" = "true" ]; then
		radeon dac on
		radeon light on
	fi
	# We might need to do one or many of these quirks
	if [ "${DISPLAY_QUIRK_VBE_POST}" = "true" ]; then
		vbe post
		sleep 0.1
	fi
	if [ "${DISPLAY_QUIRK_VBESTATE_RESTORE}" = "true" ]; then
		vbe vbestate restore < /var/run/vbestate
	fi
	if [ "${DISPLAY_QUIRK_VBEMODE_RESTORE}" = "true" ]; then
		vbe vbemode set "$(cat /var/run/vbemode)"
	fi
	# based on data from s2ram
	resume_fbcon
	if [ "${DISPLAY_QUIRK_DPMS_ON}" = "true" ]; then
		vbe dpms on
	fi
	if [ "${DISPLAY_QUIRK_RESET_BRIGHTNESS}" = "true" ]; then
		reset_brightness
	fi
}


case "$1" in
	suspend|hibernate|suspend_hybrid) save_fbcon ;;
	resume)
		resume_video
		;;
	thaw)
		if [ "${HIBERNATE_RESUME_POST_VIDEO}" = "yes" ]; then
			resume_video
		fi
		;;
esac

exit $?
