#!/bin/sh
#
# Copyright 2006-2007 Richard Hughes <richard@hughsie.com>
# Copyright 2007 Peter Jones <pjones@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.

. "${PM_FUNCTIONS}"

reset_brightness()
{
	for bl in /sys/class/backlight/* ; do
		[ -f "$bl/brightness" ] || continue
		BR="$(cat $bl/brightness)"
		echo 0 > "$bl/brightness"
		echo "$BR" > "$bl/brightness"
	done
}

if command_exists vbetool; then
	vbe() { vbetool "$@"; }
else 
	vbe() { echo "vbetool not installed!" 1>&2; return 1; }
fi

if command_exists radeontool; then
	radeon() { radeontool "$@"; }
else 
	radeon() { echo "radeontool not found" 1>&2; return 1; }
fi

save_fbcon()
{
	local con
	for con in /sys/class/graphics/*/state; do
		[ -f $con ] || continue
		echo 1 >"${con}"
	done
}

resume_fbcon()
{
	local con
	for con in /sys/class/graphics/*/state; do
		[ -f $con ] || continue
		echo 0 >"${con}"
	done
}
suspend_video()
{
	# 0=nothing, 1=s3_bios, 2=s3_mode, 3=both
	if [ "${DISPLAY_QUIRK_S3_BIOS}" = "true" -a \
		"${DISPLAY_QUIRK_S3_MODE}" = "true" ]; then
		sysctl -w kernel.acpi_video_flags=3
	elif [ "${DISPLAY_QUIRK_S3_BIOS}" = "true" ]; then
		sysctl -w kernel.acpi_video_flags=1
	elif [ "${DISPLAY_QUIRK_S3_MODE}" = "true" ]; then
		sysctl -w kernel.acpi_video_flags=2
	else
		sysctl -w kernel.acpi_video_flags=0
	fi

	# We might need to do one or many of these quirks
	if [ "${DISPLAY_QUIRK_RADEON_OFF}" = "true" ]; then
		radeon dac off
		radeon light off
	fi
	if [ "${DISPLAY_QUIRK_VBESTATE_RESTORE}" = "true" ]; then
		vbe vbestate save > /var/run/vbestate
	fi
	if [ "${DISPLAY_QUIRK_VBEMODE_RESTORE}" = "true" ]; then
		vbe vbemode get > /var/run/vbemode
	fi
	if [ "${DISPLAY_QUIRK_VGA_MODE_3}" = "true" ]; then
		vbe vbemode set 3
	fi
	if [ "${DISPLAY_QUIRK_DPMS_SUSPEND}" = "true" ]; then
		vbe dpms suspend
	fi
}
resume_video()
{
	if [ "${DISPLAY_QUIRK_RADEON_OFF}" = "true" ]; then
		radeon dac on
		radeon light on
	fi
	# We might need to do one or many of these quirks
	if [ "${DISPLAY_QUIRK_VBE_POST}" = "true" ]; then
		vbe post
		sleep 0.1
	fi
	if [ "${DISPLAY_QUIRK_VBESTATE_RESTORE}" = "true" ]; then
		vbe vbestate restore < /var/run/vbestate
	fi
	if [ "${DISPLAY_QUIRK_VBEMODE_RESTORE}" = "true" ]; then
		vbe vbemode set "$(cat /var/run/vbemode)"
	fi
	# based on data from s2ram
	resume_fbcon
	if [ "${DISPLAY_QUIRK_DPMS_ON}" = "true" ]; then
		vbe dpms on
	fi
	if [ "${DISPLAY_QUIRK_RESET_BRIGHTNESS}" = "true" ]; then
		reset_brightness
	fi
}


case "$1" in
	suspend)
		save_fbcon
		suspend_video
		;;
	hibernate)
		if [ "$HIBERNATE_RESUME_POST_VIDEO" = "yes" ]; then
			suspend_video
		fi
		;;
	resume)
		resume_video
		;;
	thaw)
		if [ "${HIBERNATE_RESUME_POST_VIDEO}" = "yes" ]; then
			resume_video
		fi
		;;
esac
