Document: pm-utils
Title: Debian pm-utils Manual
Author: <insert document author here>
Abstract: This manual describes what pm-utils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pm-utils/pm-utils.sgml.gz

Format: postscript
Files: /usr/share/doc/pm-utils/pm-utils.ps.gz

Format: text
Files: /usr/share/doc/pm-utils/pm-utils.text.gz

Format: HTML
Index: /usr/share/doc/pm-utils/html/index.html
Files: /usr/share/doc/pm-utils/html/*.html

  
