#!/bin/bash
#
# Simple suspend script
#
# Copyright 2006 Red Hat, Inc.
#
# Based on work from:
#    Bill Nottingham <notting@redhat.com>
#    Peter Jones <pjones@redhat.com>
#    David Zeuthen <davidz@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

# The rule here? Simplicity.

if [ -n "$EUID" -a "$EUID" != "0" ]; then
	echo This utility may only be run by the root user. 1>&2
	exit 1
fi

export LC_COLLATE=C

. /etc/pm/functions

[ -f /sys/power/disk ] || exit 1
[ -f /sys/power/state ] || exit 1

ACTION=$(basename "$0")
ACTION=${ACTION#pm-}

case "$ACTION" in
	suspend) REVERSE=resume ;;
	hibernate) REVERSE=thaw ;;
esac

pm_main "$ACTION" "$REVERSE"

exit $?
