#!/bin/bash

# Simple suspend script
#
# Copyright 2006 Red Hat, Inc.
#
# Based on work from:
#    Bill Nottingham <notting@redhat.com>
#    Peter Jones <pjones@redhat.com>
#    David Zeuthen <davidz@redhat.com>

# The rule here? Simplicity.

. /etc/pm/functions

[ -f /sys/power/disk ] || exit 1
[ -f /sys/power/state ] || exit 1

ACTION=$(basename "$0")
ACTION=${ACTION#pm-}

pm_main "$ACTION"

exit $?
